---
title: C6320 | Microsoft Docs
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: 12
author: corob-msft
ms.author: corob
manager: jillfra
ms.openlocfilehash: 1d37a8d33f756372cd0448e94cf9f6d5e2408cf1
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 02/15/2020
ms.locfileid: "77273430"
---
# <a name="c6320"></a>C6320
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

avviso C6320: l'espressione di filtro eccezioni è la costante EXCEPTION_EXECUTE_HANDLER. Questo può mascherare le eccezioni che non sono state progettate per essere gestite  
  
 Questo avviso indica l'effetto collaterale dell'utilizzo di EXCEPTION_EXECUTE_HANDLER costante nel blocco __except. In questo caso, l'istruzione nel blocco \__except viene sempre eseguita per gestire l'eccezione, incluse le eccezioni che non si desidera gestire in una funzione specifica. Si consiglia di controllare l'eccezione prima di gestirla.  
  
## <a name="example"></a>Esempio  
 Il codice seguente genera questo avviso perché il blocco __except tenterà di gestire le eccezioni di tutti i tipi:  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Per correggere il problema, utilizzare `GetExceptionCode` per verificare la presenza di una particolare eccezione prima di gestirla, come illustrato nel codice seguente:  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>Vedere anche  
 [Istruzione try-except](https://msdn.microsoft.com/library/30d60071-ea49-4bfb-a8e6-7a420de66381)
